import { inter } from "@/config/fonts";
import "./globals.css";
import { BottomTop, Footer, TopMenu } from "@/components/index";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopMenu />
        {children}
        <BottomTop />
        <Footer />
      </body>
    </html>
  );
}