import { BottomTop, Footer, TopMenu } from "../components";
import { contentPage } from "../config/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={contentPage.className}>
        <TopMenu />
        {children}
        <BottomTop />
        <Footer />
      </body>
    </html>
  );
}